FROM node:22-alpine

ARG ALCANTARA_BUILD_VERSION=dev
ENV ALCANTARA_BUILD_VERSION=${ALCANTARA_BUILD_VERSION}

RUN npm install -g pnpm@9

WORKDIR /app

COPY package*.json ./
RUN pnpm install --no-frozen-lockfile --ignore-scripts

COPY prisma ./prisma
RUN pnpm prisma:generate

COPY . .

CMD ["pnpm", "start:dev"]
