ALTER TABLE "BroadcastSettings"
ADD COLUMN IF NOT EXISTS "streamMasterVolume" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "streamMuted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "streamSolo" BOOLEAN NOT NULL DEFAULT false;
