name: Backend Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOYMENT_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -f backend/Dockerfile -t ghcr.io/${{ github.repository }}:latest backend

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to on-premises host
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            sh -c '
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.DEPLOYMENT_TOKEN }}
            docker pull ghcr.io/${{ github.repository }}:latest

            docker stop alcantara-backend || true
            docker rm alcantara-backend || true

            LOG_STREAM_UUID=$(uuidgen)

            docker run -d --name alcantara-backend \
            -p ${{ vars.HTTP_PORT }}:${{ vars.HTTP_PORT }} \
            -e HTTP_PORT="${{ vars.HTTP_PORT }}" \
            -e PORT="${{ vars.HTTP_PORT }}" \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e COGNITO_REGION="${{ vars.AWS_REGION }}" \
            -e COGNITO_USER_POOL_ID="${{ vars.COGNITO_USER_POOL_ID }}" \
            -e COGNITO_CLIENT_ID="${{ vars.COGNITO_CLIENT_ID }}" \
            -e CONTAINERIZED=true \
            --restart=always \
            --log-driver=awslogs \
            --log-opt awslogs-region=${{ vars.AWS_REGION }} \
            --log-opt awslogs-group=${{ vars.LOGS_GROUP }} \
            --log-opt awslogs-stream="$LOG_STREAM_UUID" \
            -v ~/.aws:/root/.aws:ro \
            ghcr.io/${{ github.repository }}:latest
            '
